import requests
import json
from datetime import datetime

URL = "https://itunes.apple.com/search?term=app&country=us&entity=software&limit=200"

def get_top_apps():
    r = requests.get(URL)
    r.raise_for_status()
    data = r.json()

    apps = []

    for app in data["results"]:
        apps.append({
            "id": app.get("trackId"),
            "name": app.get("trackName"),
            "developer": app.get("sellerName"),
            "rating": app.get("averageUserRating")
        })

    return apps


def save(apps):
    filename = f"apps_{datetime.now().date()}.json"

    with open(filename, "w", encoding="utf8") as f:
        json.dump(apps, f, indent=2, ensure_ascii=False)

    print("Saved", filename)


if __name__ == "__main__":
    apps = get_top_apps()
    save(apps)
