name: Daily AppStore Tracker

on:
  schedule:
    - cron: '0 12 * * *' # запуск каждый день в 12:00 UTC
  workflow_dispatch: # возможность запускать вручную

jobs:
  fetch-apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run AppStore fetch script
        id: run-app
        run: |
          python main.py
          echo "Checking that report.json exists:"
          ls -l report.json

      - name: Upload report
        if: success()       # шаг выполнится только если main.py прошёл успешно
        uses: actions/upload-artifact@v4
        with:
          name: appstore-report
          path: report.json
